import { Reference } from "./types";

export const REFERENCES: Reference[] = [
  {
    id: 1,
    title: "O Poderoso Chefão",
    author: "Francis Ford Coppola",
    category: "film",
    link: "https://www.justwatch.com/br/filme/o-poderoso-chefao",
    guestWeek: 2,
  },
  {
    id: 2,
    title: "Con Air",
    author: "Simon West",
    category: "film",
    link: "https://www.justwatch.com/br/filme/con-air-a-rota-da-fuga",
    guestWeek: 2,
  },
  {
    id: 3,
    title: "Despedida em Las Vegas",
    author: "Mike Figgis",
    category: "film",
    link: "https://www.justwatch.com/br/filme/despedida-em-las-vegas",
    guestWeek: 2,
  },
  {
    id: 4,
    title: "A Outra Face",
    author: "John Woo",
    category: "film",
    link: "https://www.justwatch.com/br/filme/face-off-1997",
    guestWeek: 2,
  },
  {
    id: 5,
    title: "O Milagre de Berna",
    author: "Sönke Wortmann",
    category: "film",
    link: "https://www.justwatch.com/br/filme/das-wunder-von-bern",
    guestWeek: 2,
  },
  {
    id: 6,
    title: "Fuga Para a Vitória",
    author: "John Huston",
    category: "film",
    link: "https://www.justwatch.com/br/filme/fuga-para-a-vitoria",
    guestWeek: 2,
  },
  {
    id: 7,
    title: "Futebol & Guerra",
    author: "Andy Dougan",
    category: "book",
    link: "https://www.amazon.com.br/Futebol-E-Guerra-Andy-Dougan/dp/857110803X/",
    guestWeek: 2,
  },
  {
    id: 8,
    title: "O Que É Isso, Companheiro?",
    author: "Bruno Barreto",
    category: "film",
    link: "https://www.justwatch.com/br/filme/o-que-e-isso-companheiro",
    guestWeek: 2,
  },
  {
    id: 9,
    title: "O Segredo dos Seus Olhos",
    author: "Juan José Campanella",
    category: "film",
    link: "https://www.justwatch.com/br/filme/the-secret-in-their-eyes",
    guestWeek: 2,
  },
  {
    id: 10,
    title: "Revista PLACAR, outubro de 1996",
    author: "Paulo Vinícius Coelho (reportagem da Amsterdam Arena)",
    category: "print",
    link: "https://books.google.com.br/books?id=pR8NPpHtK00C",
    guestWeek: 2,
  },
  {
    id: 11,
    title: "Queridos Amigos",
    author: "Maria Adelaide Amaral",
    category: "series",
    link: "https://globoplay.globo.com/queridos-amigos/t/9jnZwpPJKk/",
    guestWeek: 2,
  },
  {
    id: 12,
    title: "Chega de Saudade",
    author: "João Gilberto",
    category: "record",
    link: "https://open.spotify.com/album/0dtfLd8TK0aJECxnXgTAZw",
    guestWeek: 2,
  },
  {
    id: 13,
    title: "Profana",
    author: "Gal Costa",
    category: "record",
    link: "https://open.spotify.com/album/3U7Lcr4znatUgBYRrxijEk",
    guestWeek: 2,
  },
  {
    id: 14,
    title: "Corcovado",
    author: "Tom Jobim",
    category: "song",
    link: "https://songwhip.com/antoniocarlosjobim3/corcovado",
    guestWeek: 2,
  },
  {
    id: 15,
    title: "O Gênio do Crime",
    author: "João Carlos Marinho",
    category: "book",
    link: "https://www.amazon.com.br/G%C3%AAnio-Crime-Aventura-Turma-Gordo/dp/8526010476",
    guestWeek: 2,
  },
  {
    id: 16,
    title: "5 Estrelas - A Conquista do Penta",
    author: "Paulo Vinícius Coelho",
    category: "book",
    link: "https://www.amazon.com.br/5-ESTRELAS-CONQUISTA-DO-PENTA/dp/6586583039",
    guestWeek: 2,
  },
  {
    id: 17,
    title: "Saúde",
    author: "Rita Lee",
    category: "record",
    link: "https://songwhip.com/rita-lee/saude",
    guestWeek: 2,
  },
  {
    id: 18,
    title: "Thriller",
    author: "Michael Jackson",
    category: "record",
    link: "https://songwhip.com/michael-jackson/thriller1982",
    guestWeek: 2,
  },
  {
    id: 19,
    title: "Greatest Hits",
    author: "Queen",
    category: "record",
    link: "https://songwhip.com/queen/greatest-hits-remastered",
    guestWeek: 2,
  },
  {
    id: 20,
    title: "A Paz",
    author: "Gilberto Gil",
    category: "song",
    link: "https://songwhip.com/gilberto-gil/a-paz",
    guestWeek: 2,
  },
  {
    id: 21,
    title: "Cores, Nomes",
    author: "Caetano Veloso",
    category: "record",
    link: "https://songwhip.com/caetano-veloso/cores-nomes",
    guestWeek: 2,
  },
  {
    id: 22,
    title: "Moneyball",
    author: "Bennett Miller",
    category: "film",
    link: "https://www.justwatch.com/br/filme/o-homem-que-mudou-o-jogo",
    guestWeek: 2,
  },
  {
    id: 23,
    title: "Um Domingo Qualquer",
    author: "Oliver Stone",
    category: "film",
    link: "https://www.justwatch.com/br/filme/um-domingo-qualquer",
    guestWeek: 2,
  },
  {
    id: 24,
    title: "Momentos Decisivos",
    author: "David Anspaugh",
    category: "film",
    link: "https://www.justwatch.com/br/filme/hoosiers",
    guestWeek: 2,
  },
  {
    id: 25,
    title: "Amantes Eternos",
    author: "Jim Jarmusch",
    category: "film",
    link: "https://www.justwatch.com/br/filme/amantes-eternos",
    guestWeek: 1,
  },
  {
    id: 26,
    title: "Blood Sugar Sex Magik",
    author: "Red Hot Chili Peppers",
    category: "record",
    link: "https://songwhip.com/red-hot-chili-peppers/bloodsugarsexmagik",
    guestWeek: 1,
  },
  {
    id: 27,
    title: "Californication",
    author: "Red Hot Chili Peppers",
    category: "video",
    link: "https://www.youtube.com/watch?v=YlUKcNNmywk",
    guestWeek: 1,
  },
  {
    id: 28,
    title: "Scar Tissue",
    author: "Red Hot Chili Peppers",
    category: "video",
    link: "https://www.youtube.com/watch?v=mzJj5-lubeM",
    guestWeek: 1,
  },
  {
    id: 29,
    title: "Let Go",
    author: "Avril Lavigne",
    category: "record",
    link: "https://songwhip.com/avril-lavigne/let-go",
    guestWeek: 1,
  },
  {
    id: 30,
    title: "Dark Necessities",
    author: "Red Hot Chili Peppers",
    category: "song",
    link: "https://songwhip.com/red-hot-chili-peppers/dark-necessities",
    guestWeek: 1,
  },
  {
    id: 31,
    title: "Rocket Power",
    author: "Nickelodeon",
    category: "series",
    link: "https://www.justwatch.com/br/serie/rocket-power",
    guestWeek: 1,
  },
  {
    id: 32,
    title: "A Lista de Schindler",
    author: "Steven Spielberg",
    category: "film",
    link: "https://www.justwatch.com/br/filme/a-lista-de-schindler",
    guestWeek: 1,
  },
  {
    id: 33,
    title: "A Onda",
    author: "Dennis Gansel",
    category: "film",
    link: "https://www.justwatch.com/br/filme/a-onda",
    guestWeek: 1,
  },
  {
    id: 34,
    title: "O Assassino",
    author: "David Fincher",
    category: "film",
    link: "https://www.justwatch.com/br/filme/the-killer-2023",
    guestWeek: 1,
  },
  {
    id: 35,
    title: "Tenet",
    author: "Christopher Nolan",
    category: "film",
    link: "https://www.justwatch.com/br/filme/tenet",
    guestWeek: 1,
  },
  {
    id: 36,
    title: "Interestelar",
    author: "Christopher Nolan",
    category: "film",
    link: "https://www.justwatch.com/br/filme/interestelar",
    guestWeek: 1,
  },
  {
    id: 37,
    title: "Clube da Luta",
    author: "David Fincher",
    category: "film",
    link: "https://www.justwatch.com/br/filme/clube-da-luta",
    guestWeek: 1,
  },
  {
    id: 38,
    title: "Brilho Eterno de uma Mente Sem Lembranças",
    author: "Michel Gondry",
    category: "film",
    link: "https://www.justwatch.com/br/filme/brilho-eterno-de-uma-mente-sem-lembrancas",
    guestWeek: 1,
  },
  {
    id: 39,
    title: "Os Sopranos",
    author: "HBO",
    category: "series",
    link: "https://www.justwatch.com/br/serie/die-sopranos",
    guestWeek: 1,
  },
  {
    id: 40,
    title: "Dr. House",
    author: "Fox",
    category: "series",
    link: "https://www.justwatch.com/br/serie/dr-house",
    guestWeek: 1,
  },
  {
    id: 39,
    title: "Karma Police",
    author: "Radiohead",
    category: "song",
    link: "https://songwhip.com/radiohead/karma-police",
    guestWeek: 1,
  },
  {
    id: 40,
    title: "Lucky Man",
    author: "The Verve",
    category: "song",
    link: "https://songwhip.com/the-verve/lucky-man",
    guestWeek: 1,
  },
];
