import { Reference } from "./types";

export const REFERENCES: Reference[] = [
  {
    id: 1,
    title: "O Poderoso Chefão",
    author: "Francis Ford Coppola",
    category: "film",
    link: "https://www.justwatch.com/br/filme/o-poderoso-chefao",
    guestWeek: 2,
  },
  {
    id: 2,
    title: "Con Air",
    author: "Simon West",
    category: "film",
    link: "https://www.justwatch.com/br/filme/con-air-a-rota-da-fuga",
    guestWeek: 2,
  },
  {
    id: 3,
    title: "Despedida em Las Vegas",
    author: "Mike Figgis",
    category: "film",
    link: "https://www.justwatch.com/br/filme/despedida-em-las-vegas",
    guestWeek: 2,
  },
  {
    id: 4,
    title: "A Outra Face",
    author: "John Woo",
    category: "film",
    link: "https://www.justwatch.com/br/filme/face-off-1997",
    guestWeek: 2,
  },
  {
    id: 5,
    title: "O Milagre de Berna",
    author: "Sönke Wortmann",
    category: "film",
    link: "https://www.justwatch.com/br/filme/das-wunder-von-bern",
    guestWeek: 2,
  },
  {
    id: 6,
    title: "Fuga Para a Vitória",
    author: "John Huston",
    category: "film",
    link: "https://www.justwatch.com/br/filme/fuga-para-a-vitoria",
    guestWeek: 2,
  },
  {
    id: 7,
    title: "Futebol & Guerra",
    author: "Andy Dougan",
    category: "book",
    link: "https://www.amazon.com.br/Futebol-E-Guerra-Andy-Dougan/dp/857110803X/",
    guestWeek: 2,
  },
  {
    id: 8,
    title: "O Que É Isso, Companheiro?",
    author: "Bruno Barreto",
    category: "film",
    link: "https://www.justwatch.com/br/filme/o-que-e-isso-companheiro",
    guestWeek: 2,
  },
  {
    id: 9,
    title: "O Segredo dos Seus Olhos",
    author: "Juan José Campanella",
    category: "film",
    link: "https://www.justwatch.com/br/filme/the-secret-in-their-eyes",
    guestWeek: 2,
  },
  {
    id: 10,
    title: "Revista PLACAR, outubro de 1996",
    author: "Paulo Vinícius Coelho (reportagem da Amsterdam Arena)",
    category: "print",
    link: "https://books.google.com.br/books?id=pR8NPpHtK00C",
    guestWeek: 2,
  },
  {
    id: 11,
    title: "Queridos Amigos",
    author: "Maria Adelaide Amaral",
    category: "series",
    link: "https://globoplay.globo.com/queridos-amigos/t/9jnZwpPJKk/",
    guestWeek: 2,
  },
  {
    id: 12,
    title: "Chega de Saudade",
    author: "João Gilberto",
    category: "record",
    link: "https://open.spotify.com/album/0dtfLd8TK0aJECxnXgTAZw",
    guestWeek: 2,
  },
  {
    id: 13,
    title: "Profana",
    author: "Gal Costa",
    category: "record",
    link: "https://open.spotify.com/album/3U7Lcr4znatUgBYRrxijEk",
    guestWeek: 2,
  },
  {
    id: 14,
    title: "Corcovado",
    author: "Tom Jobim",
    category: "song",
    link: "https://songwhip.com/antoniocarlosjobim3/corcovado",
    guestWeek: 2,
  },
  {
    id: 15,
    title: "O Gênio do Crime",
    author: "João Carlos Marinho",
    category: "book",
    link: "https://www.amazon.com.br/G%C3%AAnio-Crime-Aventura-Turma-Gordo/dp/8526010476",
    guestWeek: 2,
  },
  {
    id: 16,
    title: "5 Estrelas - A Conquista do Penta",
    author: "Paulo Vinícius Coelho",
    category: "book",
    link: "https://www.amazon.com.br/5-ESTRELAS-CONQUISTA-DO-PENTA/dp/6586583039",
    guestWeek: 2,
  },
  {
    id: 43,
    title: "Meia-Noite em Paris",
    author: "Woody Allen",
    category: "film",
    link: "https://www.justwatch.com/br/filme/midnight-in-paris",
    guestWeek: 2,
  },
  {
    id: 17,
    title: "Saúde",
    author: "Rita Lee",
    category: "record",
    link: "https://songwhip.com/rita-lee/saude",
    guestWeek: 2,
  },
  {
    id: 18,
    title: "Thriller",
    author: "Michael Jackson",
    category: "record",
    link: "https://songwhip.com/michael-jackson/thriller1982",
    guestWeek: 2,
  },
  {
    id: 19,
    title: "Greatest Hits",
    author: "Queen",
    category: "record",
    link: "https://songwhip.com/queen/greatest-hits-remastered",
    guestWeek: 2,
  },
  {
    id: 20,
    title: "A Paz",
    author: "Gilberto Gil",
    category: "song",
    link: "https://songwhip.com/gilberto-gil/a-paz",
    guestWeek: 2,
  },
  {
    id: 21,
    title: "Cores, Nomes",
    author: "Caetano Veloso",
    category: "record",
    link: "https://songwhip.com/caetano-veloso/cores-nomes",
    guestWeek: 2,
  },
  {
    id: 22,
    title: "Moneyball",
    author: "Bennett Miller",
    category: "film",
    link: "https://www.justwatch.com/br/filme/o-homem-que-mudou-o-jogo",
    guestWeek: 2,
  },
  {
    id: 23,
    title: "Um Domingo Qualquer",
    author: "Oliver Stone",
    category: "film",
    link: "https://www.justwatch.com/br/filme/um-domingo-qualquer",
    guestWeek: 2,
  },
  {
    id: 24,
    title: "Momentos Decisivos",
    author: "David Anspaugh",
    category: "film",
    link: "https://www.justwatch.com/br/filme/hoosiers",
    guestWeek: 2,
  },
  {
    id: 25,
    title: "Amantes Eternos",
    author: "Jim Jarmusch",
    category: "film",
    link: "https://www.justwatch.com/br/filme/amantes-eternos",
    guestWeek: 1,
  },
  {
    id: 26,
    title: "Blood Sugar Sex Magik",
    author: "Red Hot Chili Peppers",
    category: "record",
    link: "https://songwhip.com/red-hot-chili-peppers/bloodsugarsexmagik",
    guestWeek: 1,
  },
  {
    id: 27,
    title: "Californication",
    author: "Red Hot Chili Peppers",
    category: "video",
    link: "https://www.youtube.com/watch?v=YlUKcNNmywk",
    guestWeek: 1,
  },
  {
    id: 28,
    title: "Scar Tissue",
    author: "Red Hot Chili Peppers",
    category: "video",
    link: "https://www.youtube.com/watch?v=mzJj5-lubeM",
    guestWeek: 1,
  },
  {
    id: 29,
    title: "Let Go",
    author: "Avril Lavigne",
    category: "record",
    link: "https://songwhip.com/avril-lavigne/let-go",
    guestWeek: 1,
  },
  {
    id: 30,
    title: "Dark Necessities",
    author: "Red Hot Chili Peppers",
    category: "song",
    link: "https://songwhip.com/red-hot-chili-peppers/dark-necessities",
    guestWeek: 1,
  },
  {
    id: 31,
    title: "Rocket Power",
    author: "Nickelodeon",
    category: "series",
    link: "https://www.justwatch.com/br/serie/rocket-power",
    guestWeek: 1,
  },
  {
    id: 32,
    title: "A Lista de Schindler",
    author: "Steven Spielberg",
    category: "film",
    link: "https://www.justwatch.com/br/filme/a-lista-de-schindler",
    guestWeek: 1,
  },
  {
    id: 33,
    title: "A Onda",
    author: "Dennis Gansel",
    category: "film",
    link: "https://www.justwatch.com/br/filme/a-onda",
    guestWeek: 1,
  },
  {
    id: 34,
    title: "O Assassino",
    author: "David Fincher",
    category: "film",
    link: "https://www.justwatch.com/br/filme/the-killer-2023",
    guestWeek: 1,
  },
  {
    id: 35,
    title: "Tenet",
    author: "Christopher Nolan",
    category: "film",
    link: "https://www.justwatch.com/br/filme/tenet",
    guestWeek: 1,
  },
  {
    id: 36,
    title: "Interestelar",
    author: "Christopher Nolan",
    category: "film",
    link: "https://www.justwatch.com/br/filme/interestelar",
    guestWeek: 1,
  },
  {
    id: 37,
    title: "Clube da Luta",
    author: "David Fincher",
    category: "film",
    link: "https://www.justwatch.com/br/filme/clube-da-luta",
    guestWeek: 1,
  },
  {
    id: 38,
    title: "Brilho Eterno de uma Mente Sem Lembranças",
    author: "Michel Gondry",
    category: "film",
    link: "https://www.justwatch.com/br/filme/brilho-eterno-de-uma-mente-sem-lembrancas",
    guestWeek: 1,
  },
  {
    id: 39,
    title: "Os Sopranos",
    author: "HBO",
    category: "series",
    link: "https://www.justwatch.com/br/serie/die-sopranos",
    guestWeek: 1,
  },
  {
    id: 40,
    title: "Dr. House",
    author: "Fox",
    category: "series",
    link: "https://www.justwatch.com/br/serie/dr-house",
    guestWeek: 1,
  },
  {
    id: 41,
    title: "Karma Police",
    author: "Radiohead",
    category: "song",
    link: "https://songwhip.com/radiohead/karma-police",
    guestWeek: 1,
  },
  {
    id: 42,
    title: "Lucky Man",
    author: "The Verve",
    category: "song",
    link: "https://songwhip.com/the-verve/lucky-man",
    guestWeek: 1,
  },
  {
    id: 43,
    title: "Massacre do Carandiru feat Dr. Dráuzio Varella",
    author: "Episódio Podcast Modus Operandi",
    category: "podcast",
    link: "https://open.spotify.com/episode/09ywDNCtYcATAf8fqplJju",
    guestWeek: 3,
  },
  {
    id: 44,
    title: "Prison Break",
    author: "FOX",
    category: "series",
    link: "https://www.justwatch.com/br/serie/prison-break",
    guestWeek: 3,
  },
  {
    id: 45,
    title: "CSI",
    author: "CBS",
    category: "series",
    link: "https://www.justwatch.com/br/serie/csi-crime-sob-investigacao",
    guestWeek: 3,
  },
  {
    id: 46,
    title: "Carandiru",
    author: "Hector Babenco",
    category: "film",
    link: "https://www.justwatch.com/br/filme/carandiru",
    guestWeek: 3,
  },
  {
    id: 47,
    title: "O Assassino Possuído",
    author: "Episódio Podcast Modus Operandi",
    category: "podcast",
    link: "https://open.spotify.com/episode/5ISmWyc4fRB3GOUsNjkOeG",
    guestWeek: 3,
  },
  {
    id: 48,
    title: "Cães de Aluguel",
    author: "Quentin Tarantino",
    category: "film",
    link: "https://www.justwatch.com/br/filme/caes-de-aluguel",
    guestWeek: 3,
  },
  {
    id: 49,
    title: "No Beast So Fierce",
    author: "Edward Bunker",
    category: "book",
    link: "https://www.amazon.com.br/No-Beast-Fierce-Edward-Bunker/dp/1842432664",
    guestWeek: 3,
  },
  {
    id: 50,
    title: "O Incêndio da Boate Kiss",
    author: "Episódio Podcast Modus Operandi",
    category: "podcast",
    link: "https://open.spotify.com/episode/4ofRumYMTCuJP2kkwVGjS6",
    guestWeek: 3,
  },
  {
    id: 51,
    title: "Todo Dia a Mesma Noite",
    author: "Netflix",
    category: "film",
    link: "https://www.justwatch.com/br/serie/todo-dia-a-mesma-noite",
    guestWeek: 3,
  },
  {
    id: 52,
    title: "Boate Kiss: A Tragédia de Santa Maria",
    author: "Globoplay",
    category: "series",
    link: "https://globoplay.globo.com/boate-kiss-a-tragedia-de-santa-maria/t/5fCzHGvMNY/",
    guestWeek: 3,
  },
  {
    id: 53,
    title: "Eu Não Entendi Matrix",
    author: "Gangrena Gasosa",
    category: "song",
    link: "https://open.spotify.com/track/1gls9YOScQ7PC3wu7Rl0ZC?si=6fe1794d6f8a4e4c",
    guestWeek: 3,
  },
  {
    id: 54,
    title: "Making of de Matrix",
    author: "",
    category: "video",
    link: "https://www.youtube.com/watch?v=qpW_JHUEyQg",
    guestWeek: 3,
  },
  {
    id: 55,
    title: "Art Attack",
    author: "Disney",
    category: "series",
    link: "https://www.justwatch.com/br/serie/art-attack",
    guestWeek: 3,
  },
  {
    id: 56,
    title: "Mussum - O Filmis",
    author: "Silvio Guindane",
    category: "film",
    link: "https://www.justwatch.com/br/filme/mussum-o-filmis",
    guestWeek: 3,
  },
  {
    id: 57,
    title: "Nosso Sonho",
    author: "Eduardo Albegaria",
    category: "film",
    link: "https://www.justwatch.com/br/filme/nosso-sonho",
    guestWeek: 3,
  },
  {
    id: 58,
    title: "Fim",
    author: "Globoplay",
    category: "series",
    link: "https://www.justwatch.com/br/serie/fim",
    guestWeek: 3,
  },
  {
    id: 59,
    title: "Mr. Robot",
    author: "USA Network",
    category: "series",
    link: "https://www.justwatch.com/br/serie/mr-robot",
    guestWeek: 3,
  },
  {
    id: 60,
    title: "11 de Setembro",
    author: "Episódio Podcast Modus Operandi",
    category: "podcast",
    link: "https://open.spotify.com/episode/7ky5OLM4AlU45IDfKA0KYS",
    guestWeek: 3,
  },
  {
    id: 61,
    title: "O Sequestro do Voo 375",
    author: "Episódio Podcast Modus Operandi",
    category: "podcast",
    link: "https://open.spotify.com/episode/2dtbm2Auzv82H8MesQp95m",
    guestWeek: 3,
  },
  {
    id: 62,
    title: "A Mágica da Arrumação",
    author: "Marie Kondo",
    category: "book",
    link: "https://www.amazon.com.br/m%C3%A1gica-arrumac%C3%A3o-Marie-Kondo/dp/854310209X/",
    guestWeek: 3,
  },
  {
    id: 63,
    title: "Toy Story",
    author: "John Lasseter",
    category: "film",
    link: "https://www.justwatch.com/br/filme/toy-story-os-rivais",
    guestWeek: 3,
  },
  {
    id: 64,
    title: "O Clone",
    author: "Globoplay",
    category: "series",
    link: "https://www.justwatch.com/br/serie/o-clone",
    guestWeek: 3,
  },
  {
    id: 65,
    title: "Joy",
    author: "David O. Russell",
    category: "film",
    link: "https://www.justwatch.com/br/filme/joy",
    guestWeek: 3,
  },
];
